version: '3.8'

services:
  mongodb:
    image: mongo:5.0.15
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    ports:
      - 27018:27017
    volumes:
      - mongodb_data_container:/data/db

  adminmongo:
    image: mrvautin/adminmongo
    container_name: adminmongo
    restart: unless-stopped
    ports:
      - "9090:1234" # Truy cập tại http://localhost:9090
    environment:
      - HOST=0.0.0.0
    volumes:
      - adminmongo_data:/config
    depends_on:
      - mongodb

volumes:
  mongodb_data_container:
  adminmongo_data:

 # docker compose -p mongodb up -d
 # mongodb://root:123456@localhost:27018/